# Distribution

In [1]:
import numpy as np

In [2]:
np.random.rand()

0.4540792059866863

In [3]:
np.random.rand(10)

array([0.2785037 , 0.53478204, 0.83755134, 0.05386127, 0.49487496,
       0.69228401, 0.99262222, 0.190082  , 0.9131884 , 0.59489461])

In [6]:
np.random.randn(10)

array([-2.37074804, -0.46157068, -3.07177017,  1.46449752, -1.25809677,
        1.56435901, -0.07054621,  1.04774292,  1.39619673,  0.33609395])

In [13]:
np.random.randint(10)

2

In [14]:
np.random.randint(10,20)

15

In [15]:
np.random.randint(10,20,6)

array([18, 11, 18, 11, 15, 19])

In [17]:
np.random.randint(10,20,6).reshape(2,3)

array([[14, 14, 10],
       [15, 15, 12]])

In [18]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [19]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
arr = np.arange(1,26).reshape(5,5)

In [21]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
arr[3][4]

20

In [31]:
arr[2:3,2:4] 

array([[13, 14]])

In [36]:
arr[0:3,1:3]

array([[ 2,  3],
       [ 7,  8],
       [12, 13]])

In [37]:
arr[3:5,0:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [38]:
arr[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [41]:
arr[2:4,1:4]

array([[12, 13, 14],
       [17, 18, 19]])

In [42]:
arr[1:5,1:2]

array([[ 7],
       [12],
       [17],
       [22]])

In [47]:
arr[[0,4],[0,4]]

array([ 1, 25])

In [48]:
arr[[0,3],[1,3]]

array([ 2, 19])

In [50]:
arr[[0,3],[3,1]]

array([ 4, 17])

In [51]:
arr.sum()

325

In [57]:
arr[0:,0:1].sum()

55

In [62]:
arr.sum(0)

array([55, 60, 65, 70, 75])

In [63]:
arr.sum(1)

array([ 15,  40,  65,  90, 115])

In [64]:
arr.sum(axis = 0)

array([55, 60, 65, 70, 75])

In [65]:
arr.sum(axis = 1)

array([ 15,  40,  65,  90, 115])

In [66]:
arr1 = np.arange(0,11)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
arr1*arr1

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [68]:
arr1**arr1

array([         1,          1,          4,         27,        256,
             3125,      46656,     823543,   16777216,  387420489,
       1410065408], dtype=int32)

In [69]:
arr1/arr1

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [70]:
1/arr1

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [71]:
2 * arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [73]:
np.log(arr1)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [75]:
arr2 = arr1[3:7]

In [76]:
arr2

array([3, 4, 5, 6])

In [78]:
arr2[1:3] = 75

In [79]:
arr2

array([ 3, 75, 75,  6])

In [80]:
arr1

array([ 0,  1,  2,  3, 75, 75,  6,  7,  8,  9, 10])